export const CarBrands = [
  'TOYOTA', 'HONDA', 'FORD', 'CHEVROLET', 'BMW', 'MERCEDES BENZ', 'AUDI', 'VOLKSWAGEN',
  'PORSCHE', 'FERRARI', 'LAMBORGHINI', 'MASERATI', 'JAGUAR', 'LAND ROVER', 'TESLA',
  'HYUNDAI', 'KIA', 'NISSAN', 'MAZDA', 'SUBARU', 'LEXUS', 'ACURA', 'INFINITI',
  'VOLVO', 'BENTLEY', 'ROLLS ROYCE', 'ASTON MARTIN', 'MCLAREN', 'BUGATTI', 'MINI',
  'CHRYSLER', 'DODGE', 'JEEP', 'RAM', 'CADILLAC', 'BUICK', 'GMC', 'LINCOLN',
  'ALFA ROMEO', 'FIAT', 'PEUGEOT', 'RENAULT', 'CITROEN', 'OPEL', 'SEAT', 'SKODA'
];