export const DesignerBrands = [
  'GUCCI', 'LOUIS VUITTON', 'PRADA', 'HERMES', 'CHANEL', 'DIOR', 'BALENCIAGA',
  'VERSACE', 'FENDI', 'BURBERRY', 'SAINT LAURENT', 'VALENTINO', 'GIVENCHY',
  'ALEXANDER MCQUEEN', 'BOTTEGA VENETA', 'CARTIER', 'ROLEX', 'OMEGA', 'TAG HEUER',
  'TIFFANY AND CO', 'BULGARI', 'SALVATORE FERRAGAMO', 'RALPH LAUREN', 'CALVIN KLEIN',
  'TOMMY HILFIGER', 'MICHAEL KORS', 'COACH', 'KATE SPADE', 'MARC JACOBS', 'CELINE'
];