export const FashionBrands = [
  'NIKE', 'ADIDAS', 'PUMA', 'REEBOK', 'NEW BALANCE', 'UNDER ARMOUR',
  'CONVERSE', 'VANS', 'FILA', 'ASICS', 'SKECHERS', 'BROOKS', 'HOKA',
  'ON RUNNING', 'SALOMON', 'THE NORTH FACE', 'PATAGONIA', 'COLUMBIA',
  'ARC TERYX', 'MAMMUT', 'MONCLER', 'CANADA GOOSE', 'SUPREME', 'STUSSY'
];