export const TechBrands = [
  'APPLE', 'SAMSUNG', 'GOOGLE', 'MICROSOFT', 'AMAZON', 'FACEBOOK', 'TWITTER', 'INSTAGRAM',
  'TIKTOK', 'SNAPCHAT', 'LINKEDIN', 'PINTEREST', 'NETFLIX', 'SPOTIFY', 'YOUTUBE',
  'INTEL', 'AMD', 'NVIDIA', 'CISCO', 'IBM', 'ORACLE', 'SALESFORCE', 'ADOBE',
  'SONY', 'LG', 'PANASONIC', 'PHILIPS', 'DELL', 'HP', 'LENOVO', 'ASUS', 'ACER'
];