export const Celebrities = {
  Actors: [
    'TOM HANKS', 'MORGAN FREEMAN', 'LEONARDO DICAPRIO', 'BRAD PITT', 'JOHNNY DEPP',
    'ROBERT DE NIRO', 'AL PACINO', 'DENZEL WASHINGTON', 'MERYL STREEP', 'JULIA ROBERTS',
    'ANGELINA JOLIE', 'JENNIFER LAWRENCE', 'EMMA STONE', 'SCARLETT JOHANSSON',
    'HARRISON FORD', 'SAMUEL L JACKSON', 'WILL SMITH', 'TOM CRUISE', 'NICOLE KIDMAN',
    'CATE BLANCHETT', 'ANTHONY HOPKINS', 'GARY OLDMAN', 'DANIEL DAY LEWIS',
    'CHRISTIAN BALE', 'HEATH LEDGER', 'ROBIN WILLIAMS', 'JIM CARREY', 'EDDIE MURPHY',
    'STEVE CARELL', 'BILL MURRAY', 'EMMA WATSON', 'DANIEL RADCLIFFE', 'HUGH JACKMAN',
    'RUSSELL CROWE', 'MATT DAMON', 'BEN AFFLECK', 'GEORGE CLOONEY', 'SANDRA BULLOCK',
    'ANNE HATHAWAY', 'NATALIE PORTMAN', 'CHARLIZE THERON', 'VIOLA DAVIS',
    'MORGAN FREEMAN', 'SAMUEL L JACKSON', 'DENZEL WASHINGTON', 'SIDNEY POITIER'
  ],
  Athletes: [
    'MICHAEL JORDAN', 'LEBRON JAMES', 'KOBE BRYANT', 'MAGIC JOHNSON', 'LARRY BIRD',
    'WAYNE GRETZKY', 'MUHAMMAD ALI', 'MIKE TYSON', 'FLOYD MAYWEATHER', 'MANNY PACQUIAO',
    'TIGER WOODS', 'JACK NICKLAUS', 'ROGER FEDERER', 'RAFAEL NADAL', 'SERENA WILLIAMS',
    'VENUS WILLIAMS', 'PELE', 'DIEGO MARADONA', 'LIONEL MESSI', 'CRISTIANO RONALDO',
    'DAVID BECKHAM', 'ZINEDINE ZIDANE', 'RONALDO', 'NEYMAR', 'MICHAEL PHELPS',
    'USAIN BOLT', 'CARL LEWIS', 'JESSE OWENS', 'JACKIE ROBINSON', 'BABE RUTH',
    'WILLIE MAYS', 'HANK AARON', 'MICKEY MANTLE', 'TED WILLIAMS', 'CY YOUNG',
    'KAREEM ABDUL JABBAR', 'WILT CHAMBERLAIN', 'BILL RUSSELL', 'SHAQUILLE ONEAL',
    'STEPHEN CURRY', 'KEVIN DURANT', 'GIANNIS ANTETOKOUNMPO', 'KAWHI LEONARD'
  ],
  'Social Activists': [
    'MARTIN LUTHER KING', 'MALCOLM X', 'NELSON MANDELA', 'MAHATMA GANDHI',
    'MOTHER TERESA', 'DALAI LAMA', 'DESMOND TUTU', 'ROSA PARKS', 'HARVEY MILK',
    'CESAR CHAVEZ', 'GLORIA STEINEM', 'BETTY FRIEDAN', 'SUSAN B ANTHONY',
    'HARRIET TUBMAN', 'FREDERICK DOUGLASS', 'JOHN LEWIS', 'HARVEY BERNARD MILK',
    'ANGELA DAVIS', 'MAYA ANGELOU', 'JAMES BALDWIN', 'AUDRE LORDE', 'BELL HOOKS',
    'CORETTA SCOTT KING', 'DOROTHY HEIGHT', 'FANNIE LOU HAMER', 'IDA B WELLS',
    'MARY MCLEOD BETHUNE', 'THURGOOD MARSHALL', 'W E B DU BOIS', 'BOOKER T WASHINGTON',
    'MARCUS GARVEY', 'MEDGAR EVERS', 'BAYARD RUSTIN', 'ELLA BAKER', 'SEPTIMA CLARK',
    'DIANE NASH', 'STOKELY CARMICHAEL', 'HUEY NEWTON', 'BOBBY SEALE', 'FRED HAMPTON'
  ]
};
