export const Colors = [
  'AMARANTH', 'AMBER', 'AMETHYST', 'APRICOT', 'AQUAMARINE', 'AZURE', 'BEIGE', 'BURGUNDY',
  'BYZANTINE', 'CARDINAL', 'CARMINE', 'CELADON', 'CERULEAN', 'CHARTREUSE', 'COBALT',
  'COPPER', 'CORAL', 'CRIMSON', 'CYAN', 'EMERALD', 'FUCHSIA', 'GOLD', 'INDIGO', 'IVORY',
  'JADE', 'LAVENDER', 'LILAC', 'MAGENTA', 'MAROON', 'MAUVE', 'NAVY', 'OCHRE', 'OLIVE',
  'ORANGE', 'ORCHID', 'PEACH', 'PERIWINKLE', 'PINK', 'PLATINUM', 'PLUM', 'PUCE',
  'PURPLE', 'RED', 'ROSE', 'RUBY', 'RUSSET', 'RUST', 'SAFFRON', 'SALMON', 'SAPPHIRE',
  'SCARLET', 'SEPIA', 'SIENNA', 'SILVER', 'TAN', 'TAUPE', 'TEAL', 'TURQUOISE',
  'ULTRAMARINE', 'VERMILION', 'VIOLET', 'VIRIDIAN', 'WHITE', 'YELLOW', 'ZAFFRE'
];