export const Fruits = [
  'APPLE', 'APRICOT', 'AVOCADO', 'BANANA', 'BLACKBERRY', 'BLUEBERRY', 'BOYSENBERRY',
  'BREADFRUIT', 'CANTALOUPE', 'CHERRY', 'CLEMENTINE', 'COCONUT', 'CRANBERRY', 'CURRANT',
  'DATE', 'DRAGONFRUIT', 'DURIAN', 'ELDERBERRY', 'FIG', 'GOOSEBERRY', 'GRAPEFRUIT',
  'GRAPE', 'GUAVA', 'HONEYDEW', 'JACKFRUIT', 'KIWI', 'KUMQUAT', 'LEMON', 'LIME',
  'LYCHEE', 'MANDARIN', 'MANGO', 'MANGOSTEEN', 'MULBERRY', 'NECTARINE', 'ORANGE',
  'PAPAYA', 'PASSIONFRUIT', 'PEACH', 'PEAR', 'PERSIMMON', 'PINEAPPLE', 'PLANTAIN',
  'PLUM', 'POMEGRANATE', 'POMELO', 'QUINCE', 'RAMBUTAN', 'RASPBERRY', 'SOURSOP',
  'STARFRUIT', 'STRAWBERRY', 'TAMARIND', 'TANGERINE', 'WATERMELON'
];