export const Furniture = [
  'ARMCHAIR', 'BARSTOOL', 'BASSINET', 'BENCH', 'BOOKCASE', 'BOOKSHELF', 'BUNKBED',
  'CABINET', 'CHAIR', 'CHAISE', 'CHANDELIER', 'CHEST', 'CLOSET', 'COFFEE TABLE',
  'CONSOLE', 'COUCH', 'CREDENZA', 'CUPBOARD', 'DAYBED', 'DESK', 'DINING TABLE',
  'DRESSER', 'END TABLE', 'ENTERTAINMENT CENTER', 'FOOTSTOOL', 'FUTON', 'HAMMOCK',
  'HEADBOARD', 'HUTCH', 'LAMP', 'LOVESEAT', 'MIRROR', 'NIGHTSTAND', 'OTTOMAN',
  'PANTRY', 'PIANO BENCH', 'RECLINER', 'ROCKING CHAIR', 'SECTIONAL', 'SHELF',
  'SIDEBOARD', 'SOFA', 'STOOL', 'TABLE', 'VANITY', 'WARDROBE', 'WINE RACK',
  'WRITING DESK'
];