export const Misc = {
  Food: [
    'PIZZA', 'SUSHI', 'BURGER', 'PASTA', 'TACO', 'SALAD', 'COOKIE', 'BREAD',
    'SANDWICH', 'BURRITO', 'NOODLES', 'RICE', 'CURRY', 'STEAK', 'CHICKEN', 'FISH',
    'SHRIMP', 'LOBSTER', 'CRAB', 'OYSTER', 'MUSSELS', 'CLAMS', 'SCALLOPS', 'CALAMARI',
    'PANCAKE', 'WAFFLE', 'FRENCH TOAST', 'CEREAL', 'OATMEAL', 'YOGURT', 'CHEESE',
    'ICE CREAM', 'CAKE', 'PIE', 'BROWNIE', 'CUPCAKE', 'DONUT', 'CROISSANT', 'MUFFIN',
    'APPLE', 'BANANA', 'ORANGE', 'GRAPE', 'STRAWBERRY', 'BLUEBERRY', 'RASPBERRY',
    'WATERMELON', 'PINEAPPLE', 'MANGO', 'PEACH', 'PEAR', 'PLUM', 'CHERRY'
  ],
  Sports: [
    'FOOTBALL', 'BASKETBALL', 'BASEBALL', 'SOCCER', 'TENNIS', 'GOLF', 'HOCKEY', 'RUGBY',
    'VOLLEYBALL', 'CRICKET', 'BOXING', 'WRESTLING', 'SWIMMING', 'DIVING', 'GYMNASTICS',
    'ATHLETICS', 'MARATHON', 'TRIATHLON', 'CYCLING', 'MOUNTAIN BIKING', 'SKATEBOARDING',
    'SNOWBOARDING', 'SKIING', 'ICE SKATING', 'FIGURE SKATING', 'CURLING', 'BADMINTON',
    'TABLE TENNIS', 'HANDBALL', 'WATER POLO', 'SURFING', 'WINDSURFING', 'SAILING',
    'ROWING', 'CANOEING', 'KAYAKING', 'ARCHERY', 'SHOOTING', 'FENCING', 'JUDO',
    'KARATE', 'TAEKWONDO', 'WEIGHTLIFTING', 'POWERLIFTING', 'CROSSFIT', 'PARKOUR',
    'ROCK CLIMBING', 'POLO', 'LACROSSE', 'ULTIMATE FRISBEE'
  ],
  
  Brands: {
    'Car Brands': [
      'TOYOTA', 'HONDA', 'FORD', 'CHEVROLET', 'BMW', 'MERCEDES BENZ', 'AUDI', 'VOLKSWAGEN',
      'PORSCHE', 'FERRARI', 'LAMBORGHINI', 'MASERATI', 'JAGUAR', 'LAND ROVER', 'TESLA',
      'HYUNDAI', 'KIA', 'NISSAN', 'MAZDA', 'SUBARU', 'LEXUS', 'ACURA', 'INFINITI',
      'VOLVO', 'BENTLEY', 'ROLLS ROYCE', 'ASTON MARTIN', 'MCLAREN', 'BUGATTI', 'MINI',
      'CHRYSLER', 'DODGE', 'JEEP', 'RAM', 'CADILLAC', 'BUICK', 'GMC', 'LINCOLN',
      'ALFA ROMEO', 'FIAT', 'PEUGEOT', 'RENAULT', 'CITROEN', 'OPEL', 'SEAT', 'SKODA',
      'GENESIS', 'RIVIAN', 'LUCID', 'POLESTAR', 'KARMA', 'KOENIGSEGG', 'PAGANI',
      'RIMAC', 'PININFARINA', 'GORDON MURRAY', 'HENNESSEY', 'ZENVO', 'SPYKER',
      'NOBLE', 'ARIEL', 'CATERHAM', 'MORGAN', 'LOTUS', 'ALPINE', 'DS', 'LYNK AND CO',
      'SMART', 'DACIA', 'LADA', 'TATA', 'MAHINDRA', 'PROTON', 'PERODUA', 'HOLDEN'
    ],
    'Designer Brands': [
      'GUCCI', 'LOUIS VUITTON', 'PRADA', 'HERMES', 'CHANEL', 'DIOR', 'BALENCIAGA',
      'VERSACE', 'FENDI', 'BURBERRY', 'SAINT LAURENT', 'VALENTINO', 'GIVENCHY',
      'ALEXANDER MCQUEEN', 'BOTTEGA VENETA', 'CARTIER', 'ROLEX', 'OMEGA', 'TAG HEUER',
      'TIFFANY AND CO', 'BULGARI', 'SALVATORE FERRAGAMO', 'RALPH LAUREN', 'CALVIN KLEIN',
      'TOMMY HILFIGER', 'MICHAEL KORS', 'COACH', 'KATE SPADE', 'MARC JACOBS', 'CELINE',
      'BALMAIN', 'JIMMY CHOO', 'MANOLO BLAHNIK', 'CHRISTIAN LOUBOUTIN', 'DOLCE GABBANA'
    ],
    'Tech Brands': [
      'APPLE', 'SAMSUNG', 'GOOGLE', 'MICROSOFT', 'AMAZON', 'FACEBOOK', 'TWITTER', 'INSTAGRAM',
      'TIKTOK', 'SNAPCHAT', 'LINKEDIN', 'PINTEREST', 'NETFLIX', 'SPOTIFY', 'YOUTUBE',
      'INTEL', 'AMD', 'NVIDIA', 'CISCO', 'IBM', 'ORACLE', 'SALESFORCE', 'ADOBE',
      'SONY', 'LG', 'PANASONIC', 'PHILIPS', 'DELL', 'HP', 'LENOVO', 'ASUS', 'ACER',
      'HUAWEI', 'XIAOMI', 'OPPO', 'VIVO', 'ONEPLUS', 'REALME', 'NOKIA', 'MOTOROLA'
    ],
    'Fashion Brands': [
      'NIKE', 'ADIDAS', 'PUMA', 'REEBOK', 'NEW BALANCE', 'UNDER ARMOUR',
      'CONVERSE', 'VANS', 'FILA', 'ASICS', 'SKECHERS', 'BROOKS', 'HOKA',
      'ON RUNNING', 'SALOMON', 'THE NORTH FACE', 'PATAGONIA', 'COLUMBIA',
      'ARC TERYX', 'MAMMUT', 'MONCLER', 'CANADA GOOSE', 'SUPREME', 'STUSSY',
      'BAPE', 'PALACE', 'KITH', 'UNIQLO', 'ZARA', 'H AND M', 'FOREVER 21',
      'URBAN OUTFITTERS', 'ANTHROPOLOGIE', 'FREE PEOPLE', 'ASOS', 'BOOHOO',
      'SHEIN', 'EVERLANE', 'REFORMATION', 'ALLBIRDS', 'OUTDOOR VOICES'
    ]
  },
  'Mythology': [
    'ZEUS', 'POSEIDON', 'HADES', 'ATHENA', 'APOLLO', 'ARTEMIS', 'HERMES',
    'ARES', 'APHRODITE', 'HEPHAESTUS', 'DIONYSUS', 'DEMETER', 'THOR',
    'ODIN', 'LOKI', 'FREYA', 'ANUBIS', 'OSIRIS', 'ISIS', 'HORUS', 'RA',
    'QUETZALCOATL', 'VISHNU', 'SHIVA', 'BRAHMA', 'KALI', 'GANESHA',
    'PERSEUS', 'THESEUS', 'HERCULES', 'ACHILLES', 'ODYSSEUS', 'JASON',
    'ORPHEUS', 'ICARUS', 'DAEDALUS', 'MEDUSA', 'MINOTAUR', 'HYDRA',
    'CERBERUS', 'PEGASUS', 'PHOENIX', 'CHIMERA', 'SPHINX', 'CYCLOPS',
    'CENTaur', 'SATYR', 'NYMPH', 'SIREN', 'HARPY', 'GORGON', 'VALKYRIE', 
    'FENRIR', 'JORMUNGANDR', 'SLEIPNIR', 'HEIMDALL', 'BALDR', 'TYR', 
    'NJORD', 'SKADI', 'BRAGI', 'IDUN', 'FORSETI', 'MIMIR', 'AEGIR', 
    'RAN', 'SURTR', 'YMIR', 'THRUD', 'MAGNI', 'MODI', 'VIDAR', 'VALI', 
    'HOENIR', 'LODUR', 'KVASIR', 'ULLR', 'SIF', 'NANNA', 'FRIGG', 'EOSTRE', 
    'OSTARA', 'HERMOD', 'THJAZI', 'ANGRBODA', 'SIGYN', 'GERD', 'GRID', 
    'JARNSAXA', 'BESTLA', 'FJORGYN', 'RINDR', 'SKOLL', 'HATI', 'RATATOSKR'
  ]
};
