export const Music = {
  'Classical Music': [
    'MOZART', 'BEETHOVEN', 'BACH', 'TCHAIKOVSKY', 'CHOPIN', 'VIVALDI', 'HANDEL', 'BRAHMS',
    'SCHUBERT', 'DEBUSSY', 'RACHMANINOFF', 'LISZT', 'WAGNER', 'STRAUSS', 'MAHLER',
    'DVORAK', 'GRIEG', 'SCHUMANN', 'MENDELSSOHN', 'SAINT SAENS', 'PROKOFIEV', 'STRAVINSKY',
    'SHOSTAKOVICH', 'RAVEL', 'ELGAR', 'HOLST', 'SIBELIUS', 'COPLAND', 'GERSHWIN',
    'BERNSTEIN', 'PUCCINI', 'VERDI', 'ROSSINI', 'BIZET', 'OFFENBACH', 'DONIZETTI',
    'BELLINI', 'MONTEVERDI', 'SCARLATTI', 'TELEMANN', 'PURCELL', 'BERLIOZ', 'FAURE',
    'RIMSKY KORSAKOV', 'MUSSORGSKY', 'BORODIN', 'BARTOK', 'SATIE', 'VAUGHAN WILLIAMS'
  ],
  'Pop Music': [
    'MICHAEL JACKSON', 'MADONNA', 'PRINCE', 'WHITNEY HOUSTON', 'BEYONCE', 'LADY GAGA',
    'TAYLOR SWIFT', 'ADELE', 'ED SHEERAN', 'JUSTIN BIEBER', 'ARIANA GRANDE', 'RIHANNA',
    'KATY PERRY', 'BRUNO MARS', 'JUSTIN TIMBERLAKE', 'BRITNEY SPEARS', 'CHRISTINA AGUILERA',
    'MARIAH CAREY', 'CELINE DION', 'JENNIFER LOPEZ', 'SHAKIRA', 'PINK', 'LADY GAGA',
    'SELENA GOMEZ', 'DEMI LOVATO', 'MILEY CYRUS', 'JONAS BROTHERS', 'ONE DIRECTION',
    'BACKSTREET BOYS', 'NSYNC', 'SPICE GIRLS', 'TAKE THAT', 'WESTLIFE', 'BOYZONE',
    'ABBA', 'BEE GEES', 'EAGLES', 'FLEETWOOD MAC', 'QUEEN', 'ELTON JOHN', 'BILLY JOEL',
    'PHIL COLLINS', 'CHER', 'MADONNA', 'CYNDI LAUPER', 'CULTURE CLUB', 'DURAN DURAN'
  ],
  'Rock Music': [
    'BEATLES', 'ROLLING STONES', 'LED ZEPPELIN', 'PINK FLOYD', 'WHO', 'DOORS',
    'JIMI HENDRIX', 'ERIC CLAPTON', 'BOB DYLAN', 'BRUCE SPRINGSTEEN', 'U2', 'REM',
    'NIRVANA', 'PEARL JAM', 'SOUNDGARDEN', 'ALICE IN CHAINS', 'RED HOT CHILI PEPPERS',
    'FOO FIGHTERS', 'GREEN DAY', 'BLINK 182', 'METALLICA', 'IRON MAIDEN', 'BLACK SABBATH',
    'AC DC', 'GUNS N ROSES', 'AEROSMITH', 'BON JOVI', 'DEF LEPPARD', 'VAN HALEN',
    'QUEEN', 'DAVID BOWIE', 'ELVIS PRESLEY', 'CHUCK BERRY', 'LITTLE RICHARD',
    'JERRY LEE LEWIS', 'BUDDY HOLLY', 'ROY ORBISON', 'BEACH BOYS', 'GRATEFUL DEAD',
    'JEFFERSON AIRPLANE', 'DOORS', 'CREAM', 'JETHRO TULL', 'YES', 'GENESIS',
    'PINK FLOYD', 'DEEP PURPLE', 'BLACK SABBATH', 'JUDAS PRIEST', 'KISS'
  ],
  'Hip Hop': [
    'EMINEM', 'TUPAC', 'NOTORIOUS BIG', 'JAY Z', 'KANYE WEST', 'DR DRE', 'SNOOP DOGG',
    'ICE CUBE', 'NAS', 'KENDRICK LAMAR', 'DRAKE', 'LIL WAYNE', 'NICKI MINAJ', 'CARDI B',
    'MEGAN THEE STALLION', 'TRAVIS SCOTT', 'POST MALONE', '50 CENT', 'OUTKAST', 'LAURYN HILL',
    'MISSY ELLIOTT', 'BEASTIE BOYS', 'RUN DMC', 'PUBLIC ENEMY', 'WU TANG CLAN',
    'A TRIBE CALLED QUEST', 'NWA', 'CYPRESS HILL', 'ICE T', 'LL COOL J', 'RAKIM',
    'KRS ONE', 'GRANDMASTER FLASH', 'AFRIKA BAMBAATAA', 'KURTIS BLOW', 'SALT N PEPA',
    'TLC', 'QUEEN LATIFAH', 'MC HAMMER', 'VANILLA ICE', 'YOUNG MC', 'TONE LOC',
    'DIGITAL UNDERGROUND', 'CYPRESS HILL', 'HOUSE OF PAIN', 'ARRESTED DEVELOPMENT'
  ]
};
