export const MusicalInstruments = [
  'ACCORDION', 'BAGPIPES', 'BANJO', 'BASS GUITAR', 'BASSOON', 'BONGO', 'CELLO',
  'CLARINET', 'CYMBAL', 'DIDGERIDOO', 'DOUBLE BASS', 'DRUM KIT', 'ELECTRIC GUITAR',
  'FLUTE', 'FRENCH HORN', 'GLOCKENSPIEL', 'GUITAR', 'HARMONICA', 'HARP', 'HARPSICHORD',
  'KEYBOARD', 'MANDOLIN', 'MARACAS', 'OBOE', 'ORGAN', 'PIANO', 'PICCOLO', 'RECORDER',
  'SAXOPHONE', 'SITAR', 'SYNTHESIZER', 'TAMBOURINE', 'TRIANGLE', 'TROMBONE', 'TRUMPET',
  'TUBA', 'UKULELE', 'VIOLA', 'VIOLIN', 'XYLOPHONE', 'ZITHER'
];