export const ClassicalMusic = [
  'MOONLIGHT SONATA', 'FUR ELISE', 'SYMPHONY NO 5', 'SYMPHONY NO 9',
  'THE FOUR SEASONS', 'CANON IN D', 'RIDE OF THE VALKYRIES', 'SWAN LAKE',
  'THE NUTCRACKER', 'CARMEN', 'WILLIAM TELL OVERTURE', 'BLUE DANUBE',
  'EINE KLEINE NACHTMUSIK', 'SYMPHONY NO 40', 'REQUIEM', 'AVE MARIA'
];