export const HipHop = [
  'LOSE YOURSELF', 'STAN', 'CALIFORNIA LOVE', 'DEAR MAMA',
  'EMPIRE STATE OF MIND', 'GOLD DIGGER', 'IN DA CLUB', 'ALRIGHT',
  'NUTHIN BUT A G THANG', 'JUICY', 'NY STATE OF MIND', 'C R E A M'
];