export const PopMusic = [
  'THRILLER', 'BILLIE JEAN', 'BEAT IT', 'LIKE A PRAYER', 'VOGUE',
  'PURPLE RAIN', 'WHEN DOVES CRY', 'I WILL ALWAYS LOVE YOU',
  'SINGLE LADIES', 'CRAZY IN LOVE', 'BAD ROMANCE', 'POKER FACE',
  'SHAKE IT OFF', 'BLANK SPACE', 'ROLLING IN THE DEEP', 'HELLO'
];