export const RockMusic = [
  'STAIRWAY TO HEAVEN', 'BOHEMIAN RHAPSODY', 'SWEET CHILD O MINE',
  'HOTEL CALIFORNIA', 'BACK IN BLACK', 'SMOKE ON THE WATER',
  'PURPLE HAZE', 'BORN TO RUN', 'LIGHT MY FIRE', 'LIKE A ROLLING STONE',
  'SMELLS LIKE TEEN SPIRIT', 'SWEET HOME ALABAMA', 'FREE BIRD'
];